(()=>{const tools=[
{name:'Executive Revenue Scorecard™',group:'Executive',desc:'Executive-wide revenue health, trajectory, risks and actions.',href:'',view:'overview',icon:'ER'},
{name:'Sales Call Analyzer™',group:'Sales & Conversion',desc:'Conversation intelligence and sales-call performance.',href:'https://kartikr222.github.io/Sales-Call-Analyzer/',icon:'SC'},
{name:'Offer Clarity Scorer™',group:'Sales & Conversion',desc:'Diagnose offer clarity, value communication and friction.',href:'https://kartikr222.github.io/offer-clarity-scorer/',icon:'OC'},
{name:'Pricing Analyzer™',group:'Revenue Economics',desc:'Pricing strategy and pricing leakage assessment.',href:'https://kartikr222.github.io/Pricing-Analyzer/',icon:'PA'},
{name:'Forecast Analyzer™',group:'Revenue Economics',desc:'Forecast evidence, confidence and predictability audit.',href:'https://kartikr222.github.io/Forecast-Analyzer/',icon:'FA'},
{name:'Pipeline Leak Detector™',group:'Revenue Economics',desc:'Find where pipeline value is leaking before revenue is lost.',href:'https://kartikr222.github.io/lead-to-opportunity-pipeline-leak-detector/',icon:'PL'},
{name:'Retention / Churn Analyzer™',group:'Customer & Retention',desc:'Retention exposure, churn risk and revenue-at-risk analysis.',href:'https://kartikr222.github.io/Churn-Analyzer/',icon:'RC'},
{name:'Proposal Friction Analyzer™',group:'Sales & Conversion',desc:'Identify proposal-stage friction that slows or kills revenue.',href:'https://kartikr222.github.io/Proposal-Friction-Analyzer/',icon:'PF'}
];
function init(){const top=document.querySelector('.tools');if(!top||document.querySelector('.kc-tool-trigger'))return;const b=document.createElement('button');b.className='kc-tool-trigger';b.type='button';b.setAttribute('aria-label','Open Tool Finder');b.innerHTML='<span>Tool Finder</span><kbd>Ctrl K</kbd>';top.insertBefore(b,top.firstChild);
const back=document.createElement('div');back.className='kc-tool-backdrop';back.innerHTML='<div class="kc-tool-dialog" role="dialog" aria-modal="true" aria-labelledby="kc-tool-title"><div class="kc-tool-head"><div class="kc-tool-title"><strong id="kc-tool-title">Kartik Clarity™ Tool Finder</strong><span>Find a diagnostic</span></div><input class="kc-tool-search" type="search" placeholder="Search tools or revenue problems..." autocomplete="off" aria-label="Search diagnostic tools"></div><div class="kc-tool-list"></div><div class="kc-tool-foot"><span>Open a diagnostic directly</span><span><kbd>Esc</kbd> close</span></div></div>';document.body.appendChild(back);const input=back.querySelector('.kc-tool-search'),list=back.querySelector('.kc-tool-list');
function render(q=''){const query=q.trim().toLowerCase();const groups={};tools.filter(t=>(t.name+' '+t.desc+' '+t.group).toLowerCase().includes(query)).forEach(t=>(groups[t.group]??=[]).push(t));list.innerHTML='';Object.entries(groups).forEach(([group,items])=>{const h=document.createElement('div');h.className='kc-tool-group';h.textContent=group;list.appendChild(h);items.forEach(t=>{const item=document.createElement('button');item.className='kc-tool-item';item.type='button';item.innerHTML='<span class="kc-tool-icon">'+t.icon+'</span><span class="kc-tool-copy"><strong>'+t.name+'</strong><span>'+t.desc+'</span></span>'+(t.view?'<span class="kc-tool-current">CURRENT</span>':'<span class="kc-tool-arrow">›</span>');item.addEventListener('click',()=>{if(t.view){back.classList.remove('open');document.querySelector('[data-view="'+t.view+'"]')?.click()}else if(t.href){window.location.href=t.href}});list.appendChild(item)})});if(!list.children.length)list.innerHTML='<div class="kc-tool-empty">No diagnostic matches that search.</div>'}
function open(){back.classList.add('open');render(input.value);requestAnimationFrame(()=>input.focus())}function close(){back.classList.remove('open');input.value='';render()};b.addEventListener('click',open);back.addEventListener('click',e=>{if(e.target===back)close()});input.addEventListener('input',()=>render(input.value));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}if(e.key==='Escape'&&back.classList.contains('open'))close()});render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();