(()=>{const tools=[
{name:'Executive Revenue Scorecard™',group:'Executive Workspace',desc:'Executive-wide revenue health, trajectory, risks and management actions.',action:'overview',icon:'ER',current:true},
{name:'Executive Report Generator',group:'Executive Workspace',desc:'Enter any company, year, reporting period and executive role to generate a decision-ready revenue report.',action:'report',icon:'RG'},
{name:'Revenue Evidence Review',group:'Executive Workspace',desc:'Review the evidence, data coverage and signals behind the current scorecard.',action:'overview',icon:'EV'},
{name:'Management Action Plan',group:'Executive Workspace',desc:'Turn the scorecard findings into prioritized actions, owners and next-step decisions.',action:'actions',icon:'AP'}
];
function init(){const top=document.querySelector('.tools');if(!top||document.querySelector('.kc-tool-trigger'))return;const b=document.createElement('button');b.className='kc-tool-trigger';b.type='button';b.setAttribute('aria-label','Open Tool Finder');b.innerHTML='<span>Find a tool</span><kbd>Ctrl K</kbd>';top.insertBefore(b,top.firstChild);
const back=document.createElement('div');back.className='kc-tool-backdrop';back.innerHTML='<div class="kc-tool-dialog" role="dialog" aria-modal="true" aria-labelledby="kc-tool-title"><div class="kc-tool-head"><div class="kc-tool-title"><strong id="kc-tool-title">Kartik Clarity™ Tool Finder</strong><span>Find what you need inside this scorecard</span></div><input class="kc-tool-search" type="search" placeholder="Search reports, revenue questions or actions..." autocomplete="off" aria-label="Search scorecard tools"></div><div class="kc-tool-list"></div><div class="kc-tool-foot"><span>Everything here stays inside Executive Revenue Scorecard™</span><span><kbd>Esc</kbd> close</span></div></div>';document.body.appendChild(back);const input=back.querySelector('.kc-tool-search'),list=back.querySelector('.kc-tool-list');
function render(q=''){const query=q.trim().toLowerCase();const groups={};tools.filter(t=>(t.name+' '+t.desc+' '+t.group).toLowerCase().includes(query)).forEach(t=>(groups[t.group]??=[]).push(t));list.innerHTML='';Object.entries(groups).forEach(([group,items])=>{const h=document.createElement('div');h.className='kc-tool-group';h.textContent=group;list.appendChild(h);items.forEach(t=>{const item=document.createElement('button');item.className='kc-tool-item';item.type='button';item.innerHTML='<span class="kc-tool-icon">'+t.icon+'</span><span class="kc-tool-copy"><strong>'+t.name+'</strong><span>'+t.desc+'</span></span>'+(t.current?'<span class="kc-tool-current">CURRENT</span>':'<span class="kc-tool-arrow">›</span>');item.addEventListener('click',()=>{back.classList.remove('open');if(t.action==='report'){document.querySelector('.report-builder-trigger')?.click();return}if(t.action==='overview'){document.querySelector('[data-view="overview"]')?.click();return}document.querySelector('[data-view="'+t.action+'"]')?.click()});list.appendChild(item)})});if(!list.children.length)list.innerHTML='<div class="kc-tool-empty">No scorecard tool matches that search.</div>'}
function open(){back.classList.add('open');render(input.value);requestAnimationFrame(()=>input.focus())}function close(){back.classList.remove('open');input.value='';render()};b.addEventListener('click',open);back.addEventListener('click',e=>{if(e.target===back)close()});input.addEventListener('input',()=>render(input.value));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}if(e.key==='Escape'&&back.classList.contains('open'))close()});render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();